export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_PRICES = "SET_PRICES";
export const FETCH_PRICES_FAILED = "FETCH_PRICES_FAILED";
